FROM elasticsearch:7.17.4
ENV node.name=netology_test path.data=/var/lib path.repo=/usr/share/elasticsearch/snapshots

RUN chmod -R 777 /var/lib &&  \
    mkdir /usr/share/elasticsearch/snapshots &&  \
    chmod -R 777 /usr/share/elasticsearch/snapshots


