apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-read-exec-pods-svc-ing-rolebinding
  namespace: default
subjects:
- kind: User
  name: system:serviceaccount:default:user1 # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: read-exec-pods-svc-ing # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
