apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir-volumes
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/log/nginx"
          name: test-volume
    - name: multitool
      image: praqma/network-multitool
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/tmp/multitool"
          name: test-volume
      env:
      - name: HTTP_PORT
        value: "88"
  volumes:
    - name: test-volume
      emptyDir: {}
