# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pass.pwd
      POSTGRES_DB: test_database
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./secrets:/run/secrets
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./backup:/media/postgresql/backup

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080