# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pass.pwd
      MYSQL_DATABASE: test_db
    volumes:
      - ./data:/var/lib/mysql
      - ./secrets:/run/secrets
      - ./initdb.d:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080