apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10mi-nfc
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/pv
  persistentVolumeReclaimPolicy: Delete
