---
- name: Change local setup
  hosts: localhost
  connection: local
  tasks:
    - name: Setup namespace kubernetes in "../deploy/app/qbec.yml
      ansible.builtin.blockinfile:
        path: ../deploy/app/qbec.yaml
        marker: "# {mark} {{ app_namespace }} ANSIBLE MANAGED BLOCK"
        insertbefore: '  vars:'
        block: |2
              {{ app_namespace }}:
                defaultNamespace: {{ app_namespace }}
                server: https://{{ hostvars['kube_control_plane'].ansible_host }}:8443
