version: '3.3'

networks:
  postgres:
    driver: bridge

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      # POSTGRES_DB: "test_db"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./backup:/media/postgresql/backup
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - postgres
