---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@{{ .Values.db.name }}:{{ .Values.db.service.port }}/news"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
