---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  ports:
    - name: {{ .Values.backend.name }}
      port: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Values.backend.name }}
  type: {{ .Values.backend.service.type }}