---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  ports:
    - name: {{ .Values.frontend.name }}
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  selector:
    app: {{ .Values.frontend.name }}
  type: {{ .Values.frontend.service.type }}
