---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  ports:
    - name: {{ .Values.db.name }}
      port: {{ .Values.db.service.port }}
  selector:
    app: {{ .Values.db.name }}
  type: {{ .Values.db.service.type }}
