---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: {{ .Values.db.service.port }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: news
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: my-pvc