---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.app.io/v1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.app.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
