---
kind: ClusterRole
apiVersion: rbac.authorization.app.io/v1
metadata:
  name: multus
rules:
  - apiGroups: ["app.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - events.app.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
