apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10mi-nfc
  namespace: prod
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/pv
  persistentVolumeReclaimPolicy: Delete
